export const GET_ALL_PRODUCTS_REQ = "GET_ALL_PRODUCTS_REQ"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR"


export const GET_PRODUCT_REQ = "GET_PRODUCT_REQ"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"